### ISSUE TITLE
no start

### ISSUE THREAD

**Issue by alessandrobelli** [FelipeBB/hearthstone-radar#1]
Hello!
I tried to start the script, but I receive this error:
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1

npm ERR! missing script: start
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\***\Desktop\hearthstone-radar-master\npm-debug.log

I think that package.json is missing the start option...

**Comment by FelipeBB** [comment]
Hi Alessandro,
I created an start script 5525184a6d8cba1ffdea550be71dd222431f5ea0

 Please read the Notes section before continue.
